### ISSUE TITLE
RuntimeError: pixel_shuffle expects its input's 'channel' dimension to be divisible by the square of upscale_factor, but input.size(-3)=63 is not divisible by 16

### ISSUE THREAD

**Issue by SongDaShuai** [Snowfallingplum/SHMT#1]
Thank you for your excellent work!  During my training, this error will occur at a random epoch, such as the 15th epoch this time.  May I ask how to solve this problem
```
Epoch 14: 100%|█| 138/138 [03:44<00:00,  1.63s/it, loss=0.0828, v_num=0, train/loss_simple_step=0.0829, train/loss_vlb_step=0.00129, train/loss_step=0.0829Average Epoch time: 224.80 seconds                                                                                                                           
Average Peak memory 17052.49MiB
Epoch 14: 100%|█| 138/138 [03:44<00:00,  1.63s/it, loss=0.0828, v_num=0, train/loss_simple_step=0.0829, train/loss_vlb_step=0.00129, train/loss_step=0.0829,Epoch 14, global step 1875: 'val/loss_simple_ema' was not in top 3
Epoch 15:  90%|▉| 124/138 [03:16<00:22,  1.59s/it, loss=0.0787, v_num=0, train/loss_simple_step=0.0319, train/loss_vlb_step=0.000162, train/loss_step=0.0319torch.Size([8, 64, 64, 64])
Summoning checkpoint.

Traceback (most recent call last):
  File "/mnt/data2_4t/haodong/project/SHMT-main/main.py", line 719, in <module>
    trainer.fit(model, data)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 266, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 231, in advance
    self.trainer._call_callback_hooks("on_train_batch_end", batch_end_outputs, batch, batch_idx, **extra_kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1630, in _call_callback_hooks
    self._on_train_batch_end(*args, **kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1660, in _on_train_batch_end
    callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx, 0)
  File "/mnt/data2_4t/haodong/project/SHMT-main/main.py", line 385, in on_train_batch_end
    self.log_img(pl_module, batch, batch_idx, split="train")
  File "/mnt/data2_4t/haodong/project/SHMT-main/main.py", line 353, in log_img
    images = pl_module.log_images(batch, split=split, **self.log_images_kwargs)
  File "/mnt/data2_4t/haodong/env/makeup310/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data2_4t/haodong/project/SHMT-main/ldm/models/diffusion/ddpm.py", line 1412, in log_images
    log["source_depth"] = F.pixel_shuffle(self.source_HF[:,1:,::], upscale_factor=4)
RuntimeError: pixel_shuffle expects its input's 'channel' dimension to be divisible by the square of upscale_factor, but input.size(-3)=63 is not divisible by 16
```
**This is my config：shmt_h0.yaml**
```
model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    level_of_Laplace: 0
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: makeup
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema

#    scheduler_config: # 10000 warmup steps
#      target: ldm.lr_scheduler.LambdaLinearScheduler
#      params:
#        warm_up_steps: [ 10000 ]
#        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
#        f_start: [ 1.e-6 ]
#        f_max: [ 1. ]
#        f_min: [ 1. ]

    corr_stage_config:
      target: ldm.models.correspondence.Correspondence
      params:
        in_channels_list: [22, 83, 70]
        model_channels: 224
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 3
          - 4

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 121
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: /mnt/data2_4t/haodong/project/SHMT-main/ldm/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.makeup_dataset.MakeupDataset
      params:
        is_train: True
        image_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_1000/
        seg_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_1000_parsing/
        depth_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_1000_depth/
        
    validation:
      target: ldm.data.makeup_dataset.MakeupDataset
      params:
        is_train: False
        image_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_100/
        seg_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_100_parsing/
        depth_path: /mnt/data2_4t/haodong/datasets/mtdataset/images/makeup_100_depth/

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
```

**Comment by Snowfallingplum** [comment]
Sorry, This is just a preliminary code collation and cannot be guaranteed to be completely correct. There may be some errors. I've been looking for a job lately and have been too busy. I will resubmit the organised code and pre-trained models once the job search is over.
